import { Montserrat } from "next/font/google";
import "./globals.css";
import PageContextProvider from "@/contexts/PageContext";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <PageContextProvider>
        <body className={`${montserrat.className}`}>{children}</body>
      </PageContextProvider>
    </html>
  );
}
